### ISSUE TITLE
Detouring LoadLibrary at process creation

### ISSUE THREAD

**Issue by asklar** [microsoft/Detours#105] opened 2020-04-26 14:42 UTC
I'm trying to detour LoadLibrary at process creation: imagine running an exe that references some DLL that isn't in the search path. I need to be able to detour LoadLibrary in that process, early enough that my detour ends up providing the right path to load the missing DLL from.
 
I've read the doc for [DetourCreateProcessWithDllEx](https://github.com/microsoft/Detours/wiki/DetourCreateProcessWithDllEx), specifically this paragraph:
> Execution in the process is then resumed. When execution resumes, the Windows process loader will first load the target DLL and then any other DLLs in the application's import table, before calling the application entry point.

What I can't figure out is how to ensure that my detour DLL not only gets _loaded_ first, but also has its DllMain run before the nt loader tries to resolve the rest of the DLL dependencies. 

Is this possible? Any tips on how to achieve this?

I also noticed there is a requirement of having an ordinal `@1` which I do, but I couldn't find mention of any requirements on the signature of this export, if there are any, and whether this export is supposed to be called? (it doesn't seem like it is called, at least not before all the dependencies are resolved).

**Comment by sylveon** [comment] 2020-04-26 19:00
Why not simply change the PATH variable in the `lpEnvironment` parameter of `CreateProcess`? According to https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order#search-order-for-desktop-applications the PATH will be searched as last resort in case the DLL isn't found.

I don't think you can get your DLL loaded before any load-time dynamically linked DLLs using Detours. There are ways outside of Detours, like `AppInit_DLL`, but this doesn't works in some common configurations (it's disabled when Secure Boot is on) and I wouldn't be surprised if it gets completely removed in the future.

**Comment by johnnyshaw02** [comment] 2020-04-26 19:41
`DetourCreateProcessWithDllEx` replaces the import table in the process with only your DLL, so it is the only one to get resolved early on. The original import table is not replaced until you call `DetourRestoreAfterWith` in your `DllMain` at `PROCESS_ATTACH`. After which point the import table is restored and the loader will continue to resolve dependencies. This will be done in the loader path before the import dependencies are fully resolved. In other words, your DllMain should be being called in the LdrpInitialize path prior to any execution beginning by the target process. And, since other imports are not currently listed in the import table until you call `DetorRestoreAfterWith`, no other dependencies should get loaded before you.

**Comment by sylveon** [comment] 2020-04-26 20:29
I was wrong then. I still think using detours to fix a unresolved DLL issue is killing a fly with a sledgehammer. Should just alter the child process's PATH for DLL resolution to find it.

**Comment by johnnyshaw02** [comment] 2020-04-27 03:22
@sylveon, I agree. I read past the first part stating the objective is to fix the loader search path.

**Comment by asklar** [comment] 2020-04-27 17:32
> @sylveon, I agree. I read past the first part stating the objective is to fix the loader search path.

@sylveon @johnnyshaw02 thanks for replying - it's more complicated than just redirecting the PATH env variable (e.g. the dependent DLL might have to be downloaded on the fly, etc.) and there are other requirements that necessitate detouring loadlibrary as well as other APIs.

In WinDBG I do see my detour DLL get loaded. I was following the samples which on DllMain have me do:
```
    DetourRestoreAfterWith();
    DetourTransactionBegin();
    DetourUpdateThread(GetCurrentThread());
    DetourAttach(...);
```

But if I understood correctly, `DetourRestoreAfterWith` will cause the other DLLs to be resolved? is there any way to detour LoadLibrary _before_ the loader tries to resolve the other DLLs?

**Comment by sylveon** [comment] 2020-04-27 17:35
By doing the transaction before `DetourRestoreAfterWith`

**Comment by johnnyshaw02** [comment] 2020-04-28 02:06
`DetourRestoreAfterWith` will not cause the loader to immediately resolve dependencies. It only fixes up the import table to it's original state. Once you return from your `DllMain` the load will continue resolving dependencies.

There is the notion of parallel loading introduced in Windows 10. But I don't believe it will apply here as the loader hasn't had an opportunity to populate anything for parallel loading before calling your `DllMain`.

So, the order in which you call `DetourRestoreAfterWith` is likely not important in your `DllMain`. It just needs to be called for the process to resolve and load as intended.

Without knowing the extent of your implementation. I think your problem is assuming the loader is calling `LoadLibrary`. The loader is not going to call this. If anything it is going to call `LdrLoadDll`. But, it could very well call an internal function (e.g. `LdrpLoadDll` or `LdrpLoadDllInternal`) that is not exported. Hooking a theses is more complicated to locate than an exported function. I'd recommend spending some time reversing `LdrpInitialize` to understand what is happening here.

**Comment by dtarditi** [comment] 2020-08-05 18:04
This looks like the question has been answered.

**Closed by dtarditi** 2020-08-05 18:04 UTC
